name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit with my email 21f1001205@ds.study.iitm.ac.in
        run: |
          echo "Update: $(date)" >> daily-update.txt
          
          git config --global user.email "21f1001205@ds.study.iitm.ac.in"
          git config --global user.name "DevSync Automation"
          git add daily-update.txt
          git commit -m "Daily commit update by 21f1001205@ds.study.iitm.ac.in"
          git push
